version: "3.9"
services:
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=myapp_development"
      - "MYSQL_ROOT_PASSWORD=admin"
    ports:
        - "33061:3306"
volumes:
  dbdata: